$ErrorActionPreference = "Stop"

Write-Host "Creando README.md por carpeta del backend..." -ForegroundColor Cyan

$folders = @(
  "src",
  "src\config",
  "src\db",
  "src\middlewares",
  "src\schemas",
  "src\shared",
  "src\shared\errors",
  "src\shared\responses",
  "src\shared\utils",
  "src\modules",
  "src\modules\health",
  "src\modules\auth",
  "src\modules\profiles",
  "src\modules\careers",
  "src\modules\vocational-reports",
  "src\modules\comparisons",
  "src\modules\syllabi",
  "src\modules\plans",
  "src\modules\shares",
  "src\modules\events",
  "src\modules\admin",
  "src\modules\ai",
  "docs",
  "docs\setup",
  "docs\backend",
  "docs\api",
  "docs\db",
  "json_schemas",
  "openapi",
  "sql",
  "plantuml",
  "infra",
  "infra\cloud-run",
  "scripts",
  "tests"
)

foreach ($folder in $folders) {
  New-Item -ItemType Directory -Force -Path $folder | Out-Null
}

$readmeContent = @(
  "# Documentación de carpeta",
  "",
  "## Estado actual",
  "",
  "Esta carpeta forma parte del backend local de UTP Match.",
  "",
  "El backend ya puede ejecutarse localmente con:",
  "",
  "npm run dev",
  "",
  "Base local:",
  "",
  "http://localhost:3000/v1",
  "",
  "## Configuración local actual",
  "",
  "Por ahora el backend puede funcionar sin Supabase ni Chatly usando:",
  "",
  "DATABASE_ENABLED=false",
  "CHATLY_ENABLED=false",
  "",
  "Esto permite avanzar endpoints, módulos, documentación y pruebas locales sin depender todavía de servicios externos.",
  "",
  "## Qué cambiar cuando tengamos Supabase correcto",
  "",
  "Editar el archivo .env en la raíz del backend:",
  "",
  "DATABASE_ENABLED=true",
  "DATABASE_URL=URI_OFICIAL_DE_SUPABASE",
  "",
  "Luego reiniciar:",
  "",
  "npm run dev",
  "",
  "Y probar:",
  "",
  "GET http://localhost:3000/v1/health/db",
  "",
  "## Qué cambiar cuando tengamos Chatly API Key",
  "",
  "Editar el archivo .env:",
  "",
  "CHATLY_ENABLED=true",
  "CHATLY_API_KEY=KEY_REAL_DE_CHATLY",
  "",
  "Luego probar:",
  "",
  "GET http://localhost:3000/v1/health/ai",
  "",
  "## Regla de seguridad",
  "",
  "No colocar valores reales de .env, DATABASE_URL, JWT_SECRET, CHATLY_API_KEY ni contraseñas dentro de archivos .md."
) -join "`r`n"

foreach ($folder in $folders) {
  Set-Content -Path (Join-Path $folder "README.md") -Value $readmeContent -Encoding UTF8
}

$setupContent = @(
  "# Cambios pendientes cuando tengamos Supabase y Chatly",
  "",
  "## Supabase",
  "",
  "Actualmente:",
  "",
  "DATABASE_ENABLED=false",
  "",
  "Cuando el dueño del Supabase comparta la URI correcta:",
  "",
  "DATABASE_ENABLED=true",
  "DATABASE_URL=URI_OFICIAL_DE_SUPABASE",
  "",
  "Archivos relacionados:",
  "",
  "src/config/env.ts",
  "src/db/pool.ts",
  ".env",
  "",
  "Probar:",
  "",
  "GET http://localhost:3000/v1/health/db",
  "",
  "## Chatly AI",
  "",
  "Actualmente:",
  "",
  "CHATLY_ENABLED=false",
  "CHATLY_API_KEY=PENDIENTE_CONFIGURAR",
  "",
  "Cuando tengamos la API Key:",
  "",
  "CHATLY_ENABLED=true",
  "CHATLY_API_KEY=KEY_REAL",
  "",
  "Archivos relacionados:",
  "",
  "src/config/env.ts",
  "src/modules/ai",
  ".env",
  "",
  "Probar:",
  "",
  "GET http://localhost:3000/v1/health/ai",
  "",
  "## Importante",
  "",
  "No compartir públicamente DATABASE_URL, JWT_SECRET, CHATLY_API_KEY ni password de Supabase."
) -join "`r`n"

Set-Content -Path "docs\setup\CAMBIOS_CUANDO_TENGAMOS_SUPABASE_Y_CHATLY.md" -Value $setupContent -Encoding UTF8

$requestsContent = @(
  "# Requests locales para probar backend",
  "",
  "Base URL:",
  "",
  "http://localhost:3000",
  "",
  "## Sin token",
  "",
  "GET http://localhost:3000/v1",
  "GET http://localhost:3000/v1/modules",
  "GET http://localhost:3000/v1/health",
  "GET http://localhost:3000/v1/health/db",
  "GET http://localhost:3000/v1/health/ai",
  "GET http://localhost:3000/v1/careers",
  "GET http://localhost:3000/v1/careers/software-engineering",
  "GET http://localhost:3000/v1/careers/software-engineering/curriculum",
  "GET http://localhost:3000/v1/syllabi/demo-syllabus-1",
  "GET http://localhost:3000/v1/admin/status",
  "GET http://localhost:3000/v1/ai/status",
  "",
  "## Crear invitado",
  "",
  "POST http://localhost:3000/v1/auth/guest",
  "",
  "Body:",
  "",
  "{",
  '  "displayName": "Sebas"',
  "}",
  "",
  "## Con token",
  "",
  "Header:",
  "",
  "Authorization: Bearer TU_ACCESS_TOKEN",
  "Content-Type: application/json",
  "",
  "GET http://localhost:3000/v1/auth/me",
  "GET http://localhost:3000/v1/profiles/me",
  "PATCH http://localhost:3000/v1/profiles/me",
  "POST http://localhost:3000/v1/vocational-reports",
  "GET http://localhost:3000/v1/vocational-reports/latest",
  "POST http://localhost:3000/v1/comparisons",
  "POST http://localhost:3000/v1/syllabi/demo-syllabus-1/explain",
  "POST http://localhost:3000/v1/plans",
  "GET http://localhost:3000/v1/plans/mock-plan-1",
  "POST http://localhost:3000/v1/shares"
) -join "`r`n"

Set-Content -Path "docs\api\REQUESTS_LOCALES_THUNDER.md" -Value $requestsContent -Encoding UTF8

Write-Host "README.md creados correctamente en carpetas del proyecto." -ForegroundColor Green
Write-Host "También se crearon docs\setup\CAMBIOS_CUANDO_TENGAMOS_SUPABASE_Y_CHATLY.md y docs\api\REQUESTS_LOCALES_THUNDER.md" -ForegroundColor Green
